### ISSUE TITLE
Reproducibility

### ISSUE THREAD

**Issue by RobertDurfee** [n1kn4x/timing-analysis#1]
Great article! Definitely an interesting application of Gaussian mixture models.

I've spent a few hours trying to reproduce your results. With some adjustments, I was able to reproduce the results using the slow string compare function (iterating character-by-character).  

However, I was unable to reproduce the results using Python's built-in string equality operator (`==`). My observations show very erratic comparison times, often resulting in the more-correct password (longer correct prefix) taking _less_ time to compare than the less-correct password (shorter correct prefix). Yet, even taking this into account (by switching to choosing the minimum), the GMM was unable to make consistent predictions.

I thought there might just be an error in my own implementation/logic and decided to clone your repository. Nevertheless, I got the same incorrect results. 

I am particularly interested in:
- What system you tested this on? 
- Did you have similar problems? 
- How did you overcome these problems (if you faced them)?

Overall, the GMM seems very sensitive to scale and often yields poorly fitted mixtures when the variance of the distributions are too large or too small (which is why, I assume, you multiply the query times by 10^9, yet this feels arbitrary and platform-specific).

I am interested in your thoughts! You seem quite knowledgeable in the subject and I am interested in reproducing your results.

**Comment by n1kn4x** [comment]
Hey,
I ran my experiments on a Lenovo L430 that has a Intel i5-3230M processor (2 x 2.6 GHz).
I faced some inconsistency problems where the algorithm made a lot of false predictions when I worked on the laptop (e.g. using the web browser) while the measurements where taken.
I guess this is because scheduling of the heavy-weight web browser strongly interferes with the timing measurement on my 2-core machine.
You can try to run the experiment when there are little to no other computations running on your machine.

About the 10^9 factor: Yeah, GMM is very sensitive to scale and if the scale is too small, inadequate distributions will be fit. That is the reason why i multiplied my measurements with 10^9 since I am measuring nanoseconds. This scaling could be done automatically, for example by linearly stretching the data to a 0-1000 scale.

Thank you very much for your interest and hit me up if you have more questions, I will try to answer them more quickly :)

**Comment by RobertDurfee** [comment]
Thanks so much for the response!! I took your advice and switched to a script and ran it directly on my local processor. It definitely improved the situation! The slow compare worked even better. I think I still need to tune it a little to work with the default compare operator. It sometimes works now, but still too rarely to be productive.

In regards to scaling, I tried to make the process a little more robust: I standardize the cleaned distribution (without outliers) such that the variance is 1. This seems to yield better convergence for the GMM, at least with the slow compare method.

I'll take a look at it again in a day or so and see if I can get anywhere tuning some of the parameters.

Thanks again!

**Comment by RobertDurfee** [comment]
Sorry, man. I have been unable to reproduce your results using Python's default string equality operator. (The results for the naive string compare function are still great, though!) 

For the record, I am using the following set up:
- System Model: Surface Book
- OS Name: Microsoft Windows 10 Pro
- Version: 10.0.17763 Build 17763
- Processor: Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz, 2496 Mhz, 2 Core(s), 4 Logical Processor(s)
- Python 3.7.3 32-bit

I am using Python directly on my machine (not through a Jupyter Notebook like before).

By normalizing the distributions to have a variance of 1 and lowering the 90% probability threshold, I am able to get slightly better results, but not enough to be consistent. 

If you have any more suggestions, I am definitely interested! But I will close this issue as I am no longer actively working to identify the problem and attribute the issue to platform differences.
